[project]
name = "Duck_PA"
version="0.1.0"
description="Duck practice assistant helps students learn topics through excercises."
dependencies = [
    "flask",
    "genai",
    "pydantic"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"