from Duck_PA.teachers.classteacher import ClassTeacher

def make_review_message(test_json: dict, teacher: ClassTeacher, language: str):
    """
    Builds a prompt for a review agent to check and correct a test generated by another AI agent.
    
    Args:
        test_json (dict): The JSON generated by the first agent with the 'questions' key.
        teacher (ClassTeacher): The teacher object providing context for corrections.
        language (str): Language in which questions and options should remain.
    
    Returns:
        str, str: The message and the teacher personality string.
    """
    
    personality = (
        f"You are a teacher called {teacher.name}. "
        f"Your specializations are {', '.join(teacher.specialization)} and your attitude is {teacher.attitude}. "
    )

    message = (
        f"You have received a test created by another AI agent. "
        f"Your task is to carefully review and correct it. "
        f"Check each question for correctness, clarity, and completeness. "
        f"Ensure that all questions are accurate, answerable, and specific to the topic. "
        f"For multiple choice questions, make sure there is exactly one correct answer. "
        f"Do not change the JSON schema. "
        f"All text should remain in {language}. "
        f"Reply ONLY with the corrected JSON, NOTHING ELSE.\n\n"
        f"Here is the test to review:\n{test_json}"
    )

    return message, personality
